# -*- coding: utf-8 -*-
"""Asistencia.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dEVNmG1Or-fa-6n237uN7imlbOw6Fs-K
"""

import streamlit as st
import pandas as pd
from datetime import date

# Archivo CSV donde se guardará la asistencia
CSV_FILE = 'asistencia.csv'

# Cargar el archivo CSV si ya existe
try:
    df_asistencia = pd.read_csv(CSV_FILE)
except FileNotFoundError:
    df_asistencia = pd.DataFrame(columns=['Fecha', 'Nombre', 'Asistencia'])

st.title("Registro de Asistencia")

# Seleccionar la fecha
fecha = st.date_input("Fecha de asistencia", date.today())

# Lista de estudiantes (puedes personalizarla o hacerla editable)
estudiantes = ['ALBERTO DANIEL_HILARIO ' ,	'ANA CLAUDIA_SANTIAGO ' ,	'ANDREA RUBY_QUINTERO ' ,	'ARMANDO JESUS_ALONSO ' ,	'AXEL VADHIR_OLMEDO ' ,	'BRANDON DANIEL_CAMACHO ' ,	'CARLOS DANIEL_RODRÍGUEZ ' ,	'CRISTINA_REYES ' ,	'DAVID_MEDINA ' ,	'ERIKA_SILVA ' ,	'JAIR_MATEO ' ,	'JAQUELINE_GONZALEZ ' ,	'JIMENA_HERNÁNDEZ ' ,	'JOSE ANTONIO_VELÁZQUEZ ' ,	'LESLIE PILAR_MENDOZA ' ,	'LUIS EDUARDO_ABAD ' ,	'MARIA GUADALUPE_MARRON ' ,	'MAYTE YAZMIN_PEREZ ' ,	'NAHOMY PAOLA_BARRERA ' ,	'NAOMI SARAHI_MENDOZA ' ,	'NAYDELIN SHARAI_GOMEZ ' ,	'SANDRA PAOLA_QUINTANA ' ,	'SHARON ASHLEY_ZAMACONA ' ,	'SILVIA ARISBET_VALDEZ ' ,	'VICTOR MANUEL_ÁLVAREZ ' ,	'JEAN KARLO _AREVALO ' ]

# Crear un diccionario para almacenar la asistencia
asistencia_data = {"Fecha": [], "Nombre": [], "Asistencia": []}

# Mostrar los estudiantes y permitir marcar asistencia
for estudiante in estudiantes:
    asistio = st.checkbox(f"{estudiante}", key=estudiante)
    asistencia_data["Fecha"].append(fecha)
    asistencia_data["Nombre"].append(estudiante)
    asistencia_data["Asistencia"].append("Presente" if asistio else "Ausente")

# Guardar la asistencia en el CSV al hacer clic
if st.button("Guardar Asistencia"):
    # Crear un DataFrame con la asistencia actual
    df_nueva_asistencia = pd.DataFrame(asistencia_data)

    # Añadir la nueva asistencia al DataFrame existente
    df_asistencia = pd.concat([df_asistencia, df_nueva_asistencia], ignore_index=True)

    # Guardar en el archivo CSV
    df_asistencia.to_csv(CSV_FILE, index=False)

    st.success("Asistencia guardada correctamente.")
    st.write(df_nueva_asistencia)

# Mostrar la asistencia guardada
if st.checkbox("Mostrar historial de asistencia"):
    st.write(df_asistencia)
